/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fmod_core_EffectUtils */

#ifndef _Included_org_fmod_core_EffectUtils
#define _Included_org_fmod_core_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef org_fmod_core_EffectUtils_MODE_NORMAL
#define org_fmod_core_EffectUtils_MODE_NORMAL 0L
#undef org_fmod_core_EffectUtils_MODE_LUOLI
#define org_fmod_core_EffectUtils_MODE_LUOLI 1L
#undef org_fmod_core_EffectUtils_MODE_DASHU
#define org_fmod_core_EffectUtils_MODE_DASHU 2L
#undef org_fmod_core_EffectUtils_MODE_GAOGUAI
#define org_fmod_core_EffectUtils_MODE_GAOGUAI 3L
#undef org_fmod_core_EffectUtils_MODE_KONGLING
#define org_fmod_core_EffectUtils_MODE_KONGLING 4L
#undef org_fmod_core_EffectUtils_MODE_JINGSONG
#define org_fmod_core_EffectUtils_MODE_JINGSONG 5L
/*
 * Class:     org_fmod_core_EffectUtils
 * Method:    effect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_fmod_core_EffectUtils_effect
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
